#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2025
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

_happy_opfs =
  require(
    "happy-opfs");
const
  _opfs_tools =
    require(
      "opfs-tools");
_file =
  _opfs_tools.file;

_read_stream_create =
  function
    (_input_file,
      _options) {
    const
      _file_obj =
        _file(
          _input_file);
      const
        _writer =
          _file_obj.createReader();
    return _writer;
};

function
  _write_stream_create(
    _input_file,
    _options) {
  const
    _file_obj =
      _file(
        _input_file);
    const
      _writer =
        _file_obj.createWriter();
  return _writer;
}

module.exports =
  _happy_opfs;
module.exports.createReadStream =
  _read_stream_create;
 module.exports.createWriteStream =
   _write_stream_create;
