#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2025
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

const
  _happy_opfs =
    require(
      "happy-opfs");
const
  _worker =
    require(
      "web-worker");
const
  _opfs_tools =
    require(
      "opfs-tools");
_file =
  _opfs_tools.file;

_read_stream_create =
  function
    (_input_file,
      _options) {
    const
      _file_obj =
        _file(
          _input_file);
      const
        _writer =
          _file_obj.createReader();
    return _writer;
};

function
  _write_stream_create(
    _input_file,
    _options) {
  const
    _file_obj =
      _file(
        _input_file);
    const
      _writer =
        _file_obj.createWriter();
  return _writer;
}

function
  _fs_worker_new(
    _url) {
  let
    _fs_worker;
  if ( typeof _url === 'undefined' ) {
    _url =
      "fs-worker.js";
  }
  _fs_worker =
    new _worker(
      _url);
  return _fs_worker;
}

async function
  _fs_worker_start(
    _worker_path,
    _buffer_length,
    _op_timeout) {
  let
    _agent,
    _agent_connect,
    _connect_opts,
    _fs_worker;
  if ( typeof _worker_path === 'undefined' ) {
    _worker_path =
      "fs-worker.js";
  }
  if ( typeof _buffer_length !== 'Number' ) {
    // SharedArrayBuffer size between
    // main thread and worker
    _buffer_length =
      10 * 1024 * 1024;
  }
  if ( typeof _buffer_length !== 'Number' ) {
    // SharedArrayBuffer size between
    // main thread and worker
    _op_timeout =
      10 * 1024 * 1024;
  }
  _agent_connect =
    _fs.connectSyncAgent;
  _fs_worker =
    _fs_worker_new(
      _worker_path);
  _connect_opts = {
    worker:
      _fs_worker,
    bufferLength:
      _buffer_length,
    opTimeout:
      _op_timeout
  }
  _agent =
    _agent_connect(
      _connect_opts);
  return _agent;
}

module.exports =
  _happy_opfs;
module.exports.fsWorkerNew =
  _fs_worker_new;
module.exports.fsWorkerStart =
  _fs_worker_start;
module.exports.createReadStream =
  _read_stream_create;
 module.exports.createWriteStream =
   _write_stream_create;
